Transform: AWS::Serverless-2016-10-31
Resources:
  MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs14.x
      CodeUri: ./src
      Description: My function
      Events:
        MyEvent:
          Type: Schedule
          Properties:
            Schedule: rate(5 minutes)
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonS3ReadOnlyAccess
      Environment:
        Variables:
          ENV: production
  MyLogsSubscription:
    Type: AWS::Logs::SubscriptionFilter
    Properties:
      LogGroupName: /aws/lambda/MyFunction
      FilterPattern: ""
      DestinationArn: !GetAtt MyFunction.Arn
      RetentionInDays: 7

